### ISSUE TITLE
Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by philipwalton** [darrenscerri/duplicate-package-checker-webpack-plugin#18]
I'm getting the following error when using this plugin with webpack 3.11.0. When looking at the compiler source for [`v3.11.0`](https://github.com/webpack/webpack/blob/v3.11.0/lib/Compiler.js#L172) I don't see `this.hooks.emit`, but I **do** see it when looking at version [v4.0.0](https://github.com/webpack/webpack/blob/v4.0.0/lib/Compiler.js#L29).

Is this plugin only compatible with certain webpack versions? If so, can you update the docs with version compatibility info?

Thanks!

```
TypeError: Cannot read property 'emit' of undefined
    at DuplicatePackageCheckerPlugin.apply (/Users/philipwalton/Projects/philipwalton/blog/node_modules/duplicate-package-checker-webpack-plugin/lib/index.js:59:18)
    at Compiler.apply (/Users/philipwalton/Projects/philipwalton/blog/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/philipwalton/Projects/philipwalton/blog/node_modules/webpack/lib/webpack.js:33:19)
    at createCompiler (/Users/philipwalton/Projects/philipwalton/blog/tasks/javascript.js:211:20)
    at gulp.task (/Users/philipwalton/Projects/philipwalton/blog/tasks/javascript.js:239:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by philipwalton** [comment]
Ahh, now I'm seeing you have a section on webpack versions at the bottom of the page.
